const mongoose = require('mongoose');

const ResumeSchema = new mongoose.Schema({
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    fullName: String,
    email: String,
    skills: [String],
    experience: [{
        role: String,
        company: String,
        duration: String,
        description: String
    }],
    education: [{
        degree: String,
        institution: String,
        year: String
    }],
    projects: [{
        title: String,
        description: String,
        techStack: [String]
    }],
    generatedContent: {
        type: String // Markdown or HTML content generated by AI
    }
}, { timestamps: true });

module.exports = mongoose.model('Resume', ResumeSchema);
